# Generated by Django 4.1.3 on 2022-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buapp', '0002_rename_paper_pdf_syllabus_syllabus_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
